### PR TITLE
feat: Add generic `helm_releases` variable for provisioning any number of Helm charts

### LINKED ISSUE #46: [ADDON] - Backstage
Add support for Backstage as an add-on with this Helm chart from Spotify. https://github.com/vinzscam/backstage-chart

### LINKED ISSUE #47: [ADDON] - Knative
Addon for [Knative Operator](https://knative.dev/docs/)

### LINKED ISSUE #154: Kubernetes Addon: external-snapshotter (snapshot-controller)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

We require snapshot-controller to create automated snapshots of the volumes for backup.

#### Describe the solution you would like

Add a snapshot-controller as a add-on to the blueprints. It'll be based on https://github.com/kubernetes-csi/external-snapshotter/

Since we could not find any helm chart for it it's added as a local chart in the blueprints repo it self.

#### Describe alternatives you have considered

Adding snapshot-controller to our helm deployment pipeline but we would like to converge our strategy and use only terraform and blueprints to deploy the entire infrastructure.

### LINKED ISSUE #168: [New Addons] NVIDA gpu-operator & Prometheus adapter
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

- To be able to deploy the MVP stack for GPU backed workloads using NVIDIA GPUs 

#### Describe the solution you would like

- The bare minimum stack for NVIDIA GPU backed workloads is:
	- `gpu-operator` for installing GPU driver, device-plugin, node feature discovery, GPU feature discovery, DCGM collector, etc.
	- `metrics-server`
	- `prometheus-adapter`
	- `kube-prometheus-stack`

#### Describe alternatives you have considered

- Deploy GPU operator and Prometheus adapter as standalone implementations 

#### Additional context

Example:

```hcl
module "eks_blueprints_addons" {
  source = "aws-ia/eks-blueprints-addons/aws"

  cluster_name      = module.eks.cluster_name
  cluster_endpoint  = module.eks.cluster_endpoint
  cluster_version   = module.eks.cluster_version
  oidc_provider_arn = module.eks.oidc_provider_arn
  
  enable_gpu_operator          = true
  enable_metrics_server        = true
  enable_prometheus_adapter    = true
  enable_kube_prometheus_stack = true
  }
```

### PR DESCRIPTION
**Pull request by bryantbiggs**
### What does this PR do?

- Add generic `helm_releases` variable for provisioning any number of Helm charts

### Motivation

- This addition supports creating an arbitrary number of Helm chart releases which gives users the ability to supplement the module definition with additional Helm charts if not natively supported by the module
- Resolves #168
- Resolves #154
- Resoles #97
- Resolves #47
- Resolves #46

### More

- [ ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [x] Yes, I ran `pre-commit run -a` with this PR

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by bryantbiggs** [comment]
Need to deploy and validate things are working as advertised - will switch from draft once validated

**Review by rodrigobersa — APPROVED** [review]
lgtm

**Comment by vstthomas** [comment]
How does this resolve https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/154?

I don't see it in the tests posted above or in  any examples.

**Comment by bryantbiggs** [comment]
[CSI Snapshotter](https://docs.aws.amazon.com/eks/latest/userguide/eks-add-ons.html) is an EKS addon and can be deployed today similar to how `kube-proxy` or `vpc-cni` are deployed, but by using the name `snapshot-controller`

**Comment by vstthomas** [comment]
So, it looks like this snippet will net the below config:

```hcl
module "eks_blueprints_addons" {
  source  = "aws-ia/eks-blueprints-addons/aws"
  version = "~> 1.12.0" #ensure to update this to the latest/desired version

  eks_addons = {
...
    vpc-cni = {
      most_recent = true
    }
    # This block is all that's required to get the below TF config
    snapshot-controller = {
      most_recent = true
    }
  }
  ...
}
```


```hcl
# tf state show module.eks_blueprints_addons.aws_eks_addon.this["snapshot-controller"]
resource "aws_eks_addon" "this" {
  addon_name                  = "snapshot-controller"
  addon_version               = "v6.3.2-eksbuild.1"
  arn                         = "arn:aws:eks:us-east-1:010101010101:addon/my-project/snapshot-controller/1ec82d78-73de-a6a9-3278-b4ada3x40eb1"
  cluster_name                = "my-project"
  created_at                  = "2023-12-11T22:13:06Z"
  id                          = "my-project:snapshot-controller"
  modified_at                 = "2023-12-11T22:13:48Z"
  preserve                    = true
  resolve_conflicts_on_create = "OVERWRITE"
  resolve_conflicts_on_update = "OVERWRITE"
  tags                        = {}
  tags_all = {
    "env"     = "stage"
    "project" = "my-project"
  }

  timeouts {}
}
```

I now see the controller running on the cluster. Thanks for the assist 🙏 
image

### Follow-up:

There are [3 components](https://github.com/kubernetes-csi/external-snapshotter/tree/master/deploy/kubernetes) to this:

* the controller ✅ 
* the snapshotter
* the webhook

Is the remaining configuration (for snapshotter/webhook) the
 * client responsibility, or
 * are there AWS docs that explain proper config for AWS?

**Comment by luigirende** [comment]
Knative doesn't have an official helm chart. Is it possible integrate it as add-on?

**Pull request merged**
