### PR TITLE
refactor: Replace EKS addon sub-modules with generic implementation

### PR DESCRIPTION
**Pull request by bryantbiggs**
### What does this PR do?

- Replace EKS addon sub-modules with generic implementation (copied from https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/main.tf#L375-L405) 
	- Will re-evaluate enabling cluster proportional autoscaler later when it is refactored (separate PR)
	- Once all changes have been made in this project, we can re-evaluate if the sleep timer is still necessary to wait on data plane. Removing for now to simplify
- Update variable names to match output of EKS module for continuity (also, `cluster_id` is no longer really used,  it is `cluster_name` unless running on Outposts)

### Motivation

- Provide generic implementation for any EKS addons supported, which includes support for addons vended via the AWS Marketplace. 

### More

- [ ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [x] Yes, I ran `pre-commit run -a` with this PR

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by askulkarni2 — APPROVED** [review]
Damn!!!

**Comment by maze88** [comment]
Re:
> Once all changes have been made in this project, we can re-evaluate if the sleep timer is still necessary to wait on data plane. Removing for now to simplify

I happen to have been using this module this weekend and believe the _wait_ may still be required...

I received a timeout error when provisioning:
```
│ Error: unexpected EKS Add-On (demo:aws-ebs-csi-driver) state returned during creation: timeout while waiting for state to become 'ACTIVE' (last state: 'DEGRADED', timeout: 20m0s)
│ [WARNING] Running terraform apply again will remove the kubernetes add-on and attempt to create it again effectively purging previous add-on configuration
│ 
│   with module.eks_addons.aws_eks_addon.this["aws-ebs-csi-driver"],
│   on .terraform/modules/eks_addons/main.tf line 17, in resource "aws_eks_addon" "this":
│   17: resource "aws_eks_addon" "this" {
```
and then once I reapplied (`terraform apply`), without any changes to the code, it succeeded:
```
Apply complete! Resources: 1 added, 12 changed, 1 destroyed.
```

**Comment by bryantbiggs** [comment]
thanks for reporting @maze88 - I suspect there might be some issues that are getting fixed here https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/pull/68

once we finish refactoring, we'll do some e2e tests to see how repeatable the deployment is and if we need to add the waiter back in then thats what we'll do. for now, its one less moving piece while we make some changes

**Comment by maze88** [comment]
Updating that I overcame this by adding:
```
  eks_addons_timeouts = { 
    create = "30m"
  } 
```
I tested with a fresh apply, of course.

**Pull request merged**
