### PR TITLE
feat: Update Karpenter addon to support `v0.32.1`/`v1beta1`

### PR DESCRIPTION
**Pull request by bryantbiggs**
### What does this PR do?

- Update Karpenter addon to support `v0.32.1`/`v1beta1`

### Motivation

- Resolves #<issue-number>

### More

- [ ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Yes, I ran `pre-commit run -a` with this PR

### For Moderators

- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Review by askulkarni2 — APPROVED** [review]
🚀

**Comment by bryantbiggs** [comment]
I need to dig in a bit more, was getting some segfault errors like this https://github.com/terraform-aws-modules/terraform-aws-eks/pull/2800#issuecomment-1788092763

**Comment by gytis-ivaskevicius** [comment]
I am not sure if you noticed, but FYI: karpenter chart has changed a lot between versions. I have not looked into exact changes but it is likely that the upgrade requires quite a bit more work from the values side

**Comment by momelod** [comment]
This update introduced a new bug. Karpter pods error with:
`panic: validating settings, missing field(s): aws.clusterName, aws.clusterName is required`

Reverting the module version to 1.9.0 corrects the error. Terraform plan shows the following changes it wants to make between versions and its putting the cluster_name in `settings.clusterName` instead of where it's expected at `settings.aws.clusterName`

```
  # module.kubernetes_addons.module.karpenter.helm_release.this[0] will be updated in-place
  ~ resource "helm_release" "this" {
        id                         = "karpenter"
      ~ metadata                   = [
          - {
              - app_version = "0.30.0"
              - chart       = "karpenter"
              - name        = "karpenter"
              - namespace   = "karpenter"
              - revision    = 2
              - values      = jsonencode(
                    {
                      - serviceAccount = {
                          - annotations = {
                              - "eks.amazonaws.com/role-arn" = "arn:aws:iam::999999999:role/karpenter-20231104123456789b"
                            }
                          - name        = "karpenter"
                        }
                      - settings       = {
                          - aws = {
                              - clusterEndpoint        = "https://ABCDEFGHIJKLMNOPQRSTUVWXYZ.gr7.ca-central-1.eks.amazonaws.com"
                              - clusterName            = "my-superawesomecluser"
                              - defaultInstanceProfile = "karpenter-my-superawesomecluser-20231104170235461500000001"
                              - interruptionQueueName  = "karpenter-my-superawesomecluser"
                            }
                        }
                    }
                )
              - version     = "v0.30.0"
            },
        ] -> (known after apply)
        name                       = "karpenter"
      ~ version                    = "v0.30.0" -> "v0.32.1"
        # (27 unchanged attributes hidden)

      - set {
          - name  = "settings.aws.clusterEndpoint" -> null
          - value = "https://ABCDEFGHIJKLMNOPQRSTUVWXYZ.gr7.ca-central-1.eks.amazonaws.com" -> null
        }
      - set {
          - name  = "settings.aws.clusterName" -> null
          - value = "my-superawesomecluser" -> null
        }
      - set {
          - name  = "settings.aws.defaultInstanceProfile" -> null
          - value = "karpenter-my-superawesomecluser-20231104170235461500000001" -> null
        }
      - set {
          - name  = "settings.aws.interruptionQueueName" -> null
          - value = "karpenter-my-superawesomecluser" -> null
        }
      + set {
          + name  = "settings.clusterEndpoint"
          + value = "https://ABCDEFGHIJKLMNOPQRSTUVWXYZ.gr7.ca-central-1.eks.amazonaws.com"
        }
      + set {
          + name  = "settings.clusterName"
          + value = "my-superawesomecluser"
        }
      + set {
          + name  = "settings.interruptionQueueName"
          + value = "karpenter-my-superawesomecluser"
        }

        # (2 unchanged blocks hidden)
    }

Plan: 0 to add, 2 to change, 1 to destroy.
```

```

**Comment by bryantbiggs** [comment]
Karpenter v0.32.x is using `settings.clusterName` https://github.com/aws/karpenter/blob/5d0d978b68ee57d24594a1a83cd3bbf8b47b2e87/charts/karpenter/values.yaml#L185

**Pull request merged**
