### PR TITLE
feat: Create a KEDA deployment

### LINKED ISSUE #245: [ADDON] - Keda
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### What is the outcome that you are trying to reach?

KEDA scaling the number of pods in the cluster based on the number of events that need to be processed this in combination with Karpenter can lead to better application performance and/or cost optimization

#### Describe the solution you would like

Have Keda installation available as simple as 

`enable_keda                       = true`

#### Describe alternatives you have considered

Tried using aws-ia/eks-blueprints-addon/aws but that is confusing and adds extra complexity

#### Additional context
For a functional KEDA controller there's more than just installing the helm chart. In order to e.g use the Cloudwatch scaler (or the SQS scaler, or the DynamoDB scaler etc etc) a whole bunch of IAM policies + IRSA mappings needs to be configured for it, which seems to be right in the realm of this module.

### PR DESCRIPTION
**Pull request by matheusmazzoni**
### What does this PR do?

This PR introduces the implementation of KEDA (Kubernetes Event-Driven Autoscaling) to the EKS Blueprints Addons repository. KEDA enables event-driven autoscaling for Kubernetes workloads, supporting a wide range of scalers like AWS SQS, CloudWatch, and DynamoDB. The integration is achieved by adding a simple configuration option to enable KEDA.

### Motivation

The motivation behind this PR is to provide efficient resource utilization, enhance performance by dynamically adjusting workloads, and offer broad compatibility with various event sources.
- Resolves #245

### More

- [x] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [x] Yes, I ran `pre-commit run -a` with this PR

### For Moderators

- [ ] E2E Test successfully complete before merge?

### Additional Notes

In my local environment, KEDA successfully scaled applications based on event-driven triggers.

### CODE REVIEW

**Comment by matheusmazzoni** [comment]
@bryantbiggs do you think this implementation is valid?

**Comment by bryantbiggs** [comment]
no, I do not in its current form. As previously stated, this is just re-wrapping helm which is not providing much (if any) value. Users can deploy this today without any code changes required by the module https://github.com/aws-ia/terraform-aws-eks-blueprints-addons/issues/245#issuecomment-1729329835

What benefit is there to having just Terraform wrappers around Helm charts?

**Comment by vvchik** [comment]
It is logical to onboard it as It is a very popular hpa replacement. It is popular in the same way as Karpenter is a replacement for cluster-autoscaler.

**Comment by vvchik** [comment]
The main issue in that PR is it is not supporting irsa roles, so smth like that (maybe plain and not module) should be added 

```
module "iam_assumable_role_keda" {
  source      = "terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc"
  create_role = true
  role_name   = "keda-role-${var.eks_cluster_name}"
  tags = {
    Role = "keda-role-${var.eks_cluster_name}"
  }
  # provider_url  = replace(var.eks_oidc_provider, "https://", "")
  provider_url = data.aws_eks_cluster.this.identity[0].oidc[0].issuer
  role_policy_arns = [
    "arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess",
  ]
  oidc_fully_qualified_subjects = [
    "system:serviceaccount:keda:keda-operator",
  ]
}

```


and the following helm values should become configurable variables if irsa used 

```
podIdentity:
  aws:
    irsa:
      enabled: true
      roleArn: "${keda_operator_role_arn}"    

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: ${keda_operator_role_arn}
```

**Pull request closed without merging**
